import { ArrowLeft } from "lucide-react";
import Link from "next/link";

export const metadata = {
  title: "Privacy Policy | Cookie Paradise Travel Company",
  description: "How Cookie Paradise Travel Company collects, uses and protects information submitted through its website.",
};

export default function PrivacyPolicy() {
  return (
    <main className="min-h-screen bg-[var(--sand)] text-[var(--ink)]">
      <header className="bg-[var(--navy)] text-white">
        <div className="mx-auto max-w-4xl px-5 py-10 sm:px-8">
          <Link className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--gold)] hover:underline" href="/"><ArrowLeft className="h-4 w-4" /> Back to the trip</Link>
          <h1 className="mt-6 font-serif text-4xl sm:text-6xl">Privacy Policy</h1>
          <p className="mt-3 text-white/75">Effective October 8, 2026</p>
        </div>
      </header>

      <article className="mx-auto max-w-4xl space-y-9 px-5 py-12 text-base leading-8 sm:px-8 sm:py-16">
        <section><h2 className="font-serif text-3xl">Who we are</h2><p className="mt-3 text-[var(--muted-ink)]">Cookie Paradise Travel Company LLC is a Columbus, Indiana-based travel company offering hosted small-group journeys. This policy explains how we handle information submitted through cookieparadisetravel.com.</p></section>
        <section><h2 className="font-serif text-3xl">Information we collect</h2><p className="mt-3 text-[var(--muted-ink)]">When you request a spot, we collect your name, email address, telephone number, preferred departure, party size, room preference, contact consent and any notes you choose to provide. If you identify yourself as living in a state that may have seller-of-travel registration requirements, we also collect the state you select. If space is available, a secure traveler-list form may collect each traveler’s legal name, adult or minor status, email address and, for a minor, the date of birth and the parent or guardian’s name and relationship. During booking, we may also record the confirmed booking total and whether the primary contact selects full payment or the deposit-and-installment plan. When a traveler or guardian electronically signs an agreement, we record the verified recipient email, signer name and type, date and time, required acknowledgments, agreement version and document hash, browser information and a cryptographic hash of the signer’s IP address. Please do not submit passport numbers, payment-card information, medical information or other sensitive personal information through these forms.</p></section>
        <section><h2 className="font-serif text-3xl">How we use it</h2><p className="mt-3 text-[var(--muted-ink)]">We use inquiry and traveler-list information to respond to you, discuss availability, evaluate seller-of-travel compliance before proceeding with a possible sale, prepare and deliver individual traveler agreements, verify the signer’s email address, create tamper-evident electronic-signature records, provide signed PDF copies, plan group departures, maintain business records and improve our travel offerings. Submitting an inquiry or traveler list does not create a reservation or payment obligation, and it does not guarantee that we can accept a booking.</p></section>
        <section><h2 className="font-serif text-3xl">Marketing choices</h2><p className="mt-3 text-[var(--muted-ink)]">We add your email address to our MailerLite marketing list only when you separately select the optional marketing checkbox. You may unsubscribe using the link in any marketing email. Declining marketing does not prevent us from responding to your specific trip inquiry.</p></section>
        <section><h2 className="font-serif text-3xl">Where information goes</h2><p className="mt-3 text-[var(--muted-ink)]">Inquiry, traveler and electronic-signature records are stored in the Cloudflare D1 database supporting this website and are available through a Cloudflare Access-protected owner dashboard. Inquiry details are also sent to our configured owner-notification webhook service so the owner can receive and respond to operational alerts. MailerSend delivers secure agreement links, one-time verification codes and signed PDF copies. When you separately consent to marketing, your name and email address are transmitted to MailerLite for email-list management.</p></section>
        <section><h2 className="font-serif text-3xl">Payments and Square</h2><p className="mt-3 text-[var(--muted-ink)]">If we accept your booking, the primary contact may use a secure link to choose full payment or the deposit-and-installment plan. After that choice is confirmed, we send the customer’s name, email address, telephone number, confirmed booking total and payment schedule to Square, and the customer continues to Square’s hosted payment page. Square creates and emails one invoice containing the $500 per traveler reservation deposit and scheduled monthly balance installments or, when applicable, full payment. A customer choosing installments first reviews the Square invoice and may choose to save a card securely with Square while paying the deposit. After the deposit is received, the customer may use a separate secure link showing the exact remaining Square schedule to authorize automatic installments. If automatic installments are activated, this website records the authorization, activation status, card brand and last four digits, but not the full card number. Square processes payments and sends scheduled notices through its systems. Cookie Paradise Travel Company does not receive or store your full payment-card or bank-account number on this website.</p></section>
        <section><h2 className="font-serif text-3xl">Sharing and service providers</h2><p className="mt-3 text-[var(--muted-ink)]">We do not sell your personal information. We use Cloudflare for website hosting, access control, database services, PDF generation and Cloudflare Turnstile (bot protection); MailerSend for operational and electronic-signature emails; MailerLite for consented email marketing; Square for invoices and payment processing; and an owner-notification webhook service for operational alerts. We may also disclose information when required by law. Service providers receive only the information reasonably necessary for their role.</p></section>
        <section><h2 className="font-serif text-3xl">Retention and security</h2><p className="mt-3 text-[var(--muted-ink)]">We retain inquiry and booking information for as long as reasonably necessary to provide requested services, satisfy legal or accounting obligations and protect our business. Electronic-signature records and their signed agreement copies are retained until at least seven years after the associated trip ends. We use email verification, access controls, cryptographic document and record checks, and other reasonable administrative and technical safeguards, but no internet transmission or storage system is completely secure.</p></section>
        <section><h2 className="font-serif text-3xl">Your choices</h2><p className="mt-3 text-[var(--muted-ink)]">You may ask to review, correct or delete inquiry information, subject to legal recordkeeping requirements. You can also withdraw marketing consent at any time by unsubscribing or contacting us.</p></section>
        <section><h2 className="font-serif text-3xl">Contact us</h2><p className="mt-3 text-[var(--muted-ink)]">For privacy questions or data requests, email <a className="font-semibold underline" href="mailto:trung@cookieparadise.co">trung@cookieparadise.co</a>.</p></section>
      </article>
    </main>
  );
}
